project_name: global_docker_compose
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    dir: cmd/gdc
    goos:
      - linux
      - darwin
    binary: global_docker_compose
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - 
    name: global_docker_compose
    folder: Formula
    tap:
      owner: wishabi
      name: homebrew-flipp
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    description: Standardized and centralized Docker compose command
